// Usage: node scripts/generate-favicon.js
// Output: public/favicon.ico, public/favicon.png
//
// Rasterises brand/mark.svg — which is itself generated by brand/build.mjs
// from brand/geometry.mjs. The mark is never drawn here: this script only
// converts it, so run `node brand/build.mjs` first if the geometry changed.
//
// It used to draw a typographic "K" in a flat square with CSS, which is why
// the favicon and the brand mark had drifted into two different logos.

const puppeteer = require('puppeteer');
const { PNG }   = require('pngjs');
const path = require('path');
const fs   = require('fs');
const os   = require('os');

const OUT_PATH     = path.resolve(__dirname, '../public/favicon.ico');
const OUT_PNG_PATH = path.resolve(__dirname, '../public/favicon.png');
const MARK_PATH    = path.resolve(__dirname, '../brand/mark.svg');
const SIZES        = [16, 32, 48];
/** The apple-touch / og-sized raster. */
const PNG_SIZE     = 180;

function buildHtml(size) {
  // The mark as a data URI, scaled to the icon box. An <img> rather than an
  // inline <svg> so nothing in the page's CSS can reach into the artwork.
  const svg = fs.readFileSync(MARK_PATH, 'utf8');
  const uri = `data:image/svg+xml;base64,${Buffer.from(svg).toString('base64')}`;
  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { width: ${size}px; height: ${size}px; overflow: hidden; }
  img  { width: ${size}px; height: ${size}px; display: block; }
</style>
</head>
<body><img src="${uri}" alt=""></body>
</html>`;
}

function toRGBA(pngBuf) {
  const src = PNG.sync.read(pngBuf);
  const dst = new PNG({ width: src.width, height: src.height, colorType: 6 });
  for (let i = 0; i < src.width * src.height; i++) {
    dst.data[i * 4 + 0] = src.data[i * 4 + 0];
    dst.data[i * 4 + 1] = src.data[i * 4 + 1];
    dst.data[i * 4 + 2] = src.data[i * 4 + 2];
    dst.data[i * 4 + 3] = 255;
  }
  return PNG.sync.write(dst);
}

function buildIco(pngBuffers, sizes) {
  const count   = pngBuffers.length;
  const dirSize = 6 + count * 16;
  const offsets = [];
  let offset = dirSize;
  for (const buf of pngBuffers) { offsets.push(offset); offset += buf.length; }

  const header = Buffer.alloc(6);
  header.writeUInt16LE(0, 0);
  header.writeUInt16LE(1, 2);
  header.writeUInt16LE(count, 4);

  const entries = pngBuffers.map((buf, i) => {
    const e = Buffer.alloc(16);
    const s = sizes[i];
    e.writeUInt8(s >= 256 ? 0 : s, 0);
    e.writeUInt8(s >= 256 ? 0 : s, 1);
    e.writeUInt8(0, 2);
    e.writeUInt8(0, 3);
    e.writeUInt16LE(1, 4);
    e.writeUInt16LE(32, 6);
    e.writeUInt32LE(buf.length, 8);
    e.writeUInt32LE(offsets[i], 12);
    return e;
  });

  return Buffer.concat([header, ...entries, ...pngBuffers]);
}

(async () => {
  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'favicon-'));

  const browser = await puppeteer.launch({
    headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage'],
  });

  const page = await browser.newPage();
  const pngBuffers = [];

  for (const size of SIZES) {
    const pngPath = path.join(tmpDir, `${size}.png`);
    await page.setViewport({ width: size, height: size, deviceScaleFactor: 1 });
    await page.setContent(buildHtml(size), { waitUntil: 'domcontentloaded' });
    await page.screenshot({ path: pngPath, type: 'png', clip: { x: 0, y: 0, width: size, height: size } });
    pngBuffers.push(toRGBA(fs.readFileSync(pngPath)));
  }

  // The larger raster, for surfaces that will not take an .ico.
  const pngPath = path.join(tmpDir, `${PNG_SIZE}.png`);
  await page.setViewport({ width: PNG_SIZE, height: PNG_SIZE, deviceScaleFactor: 1 });
  await page.setContent(buildHtml(PNG_SIZE), { waitUntil: 'domcontentloaded' });
  await page.screenshot({ path: pngPath, type: 'png', omitBackground: true });
  fs.mkdirSync(path.dirname(OUT_PNG_PATH), { recursive: true });
  fs.copyFileSync(pngPath, OUT_PNG_PATH);

  await browser.close();
  fs.rmSync(tmpDir, { recursive: true });

  fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
  fs.writeFileSync(OUT_PATH, buildIco(pngBuffers, SIZES));

  console.log(`✓ favicon.ico (${SIZES.join('/')}px) → ${OUT_PATH}`);
  console.log(`✓ favicon.png (${PNG_SIZE}px) → ${OUT_PNG_PATH}`);
})();
